<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>rest-assured-framework</groupId>
    <artifactId>rest-assured-framework</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>

        <restassured.version>6.0.0</restassured.version>
        <jackson.version>2.21.0</jackson.version>
        <surefire.version>3.5.4</surefire.version>
        <allure.version>2.24.0</allure.version>
        <slf4j.version>2.0.17</slf4j.version>
        <logback.version>1.4.11</logback.version>
        <testng.version>7.10.2</testng.version>

        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>


    </properties>

    <dependencies>

        <!-- ========================= -->
        <!-- Rest Assured -->
        <!-- ========================= -->
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>${restassured.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- ========================= -->
        <!-- TestNG -->
        <!-- ========================= -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>${testng.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- ========================= -->
        <!-- Jackson -->
        <!-- ========================= -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <!-- ========================= -->
        <!-- Logging -->
        <!-- ========================= -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback.version}</version>
        </dependency>

        <!-- ========================= -->
        <!-- Allure -->
        <!-- ========================= -->

        <!-- TestNG Integration -->
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-testng</artifactId>
            <version>${allure.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- Rest Assured Integration -->
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-rest-assured</artifactId>
            <version>${allure.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- JSON Schema Validator -->
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>json-schema-validator</artifactId>
            <version>${restassured.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>



    <build>

        <plugins>
            <!-- Compiler Plugin to handle Java 17 release target -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <release>17</release>
                </configuration>
            </plugin>

            <!-- ========================= -->
            <!-- Maven Surefire -->
            <!-- ========================= -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${surefire.version}</version>

                <configuration>

                    <useModulePath>false</useModulePath>

<!--                    <includes>-->
<!--                        <include>**/*Test.java</include>-->
<!--                        <include>**/*Tests.java</include>-->
<!--                    </includes>-->

                    <suiteXmlFiles>
                        <suiteXmlFile>testng.xml</suiteXmlFile>
                    </suiteXmlFiles>

                    <systemPropertyVariables>
                        <allure.results.directory>
                            ${project.build.directory}/allure-results
                        </allure.results.directory>
                    </systemPropertyVariables>

                    <testFailureIgnore>true</testFailureIgnore>

                </configuration>

            </plugin>

            <!-- ========================= -->
            <!-- Allure Maven -->
            <!-- ========================= -->
            <plugin>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-maven</artifactId>
                <version>2.12.0</version>

                <configuration>
                    <resultsDirectory>${project.build.directory}/allure-results</resultsDirectory>
                    <reportDirectory>${project.build.directory}/allure-report</reportDirectory>
                </configuration>

                <executions>
                    <execution>
                        <id>allure-report</id>
                        <phase>verify</phase>

                        <goals>
                            <goal>report</goal>
                        </goals>

                    </execution>
                </executions>

            </plugin>

        </plugins>

    </build>

</project>